config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :products
  post "products/add/:id", to: "products#add_product", as: "products_add"
  post "products/remove/:id", to: "products#remove_product", as: "products_remove"
  get "cart/show", to: "cart#show", as: "cart"
  post "cart/remove-product/:id", to: "cart#remove_product", as: "cart_remove_product"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    def show
    end

    def remove_product
        session[:product_cart].delete(params[:id])
        redirect_to cart_path
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :initialize_cart_session

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    # byebug
    p session[:product_cart].delete("#{@product.id}")
    p "kalpin"
    @product.destroy
    
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_product
    session[:product_cart][params[:id]] = 0 unless session[:product_cart][params[:id]]
    session[:product_cart][params[:id]] += 1
    redirect_to product_path(params[:id])
  end

  def remove_product
    if session[:product_cart][params[:id]] == 1
      session[:product_cart][params[:id]] = 1
    else
      session[:product_cart][params[:id]] -= 1
    end
    redirect_to product_path(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price)
    end

    def initialize_cart_session
      session[:product_cart] = {} unless session[:product_cart]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/show.html.erb
<h1>Your Cart</h1>

<% unless session[:product_cart].empty?  %>
    
        <table class="table table-hover w-50">
            <thead>
                <tr>
                <th>Product</th>
                <th>Total Amount</th>
                <th></th>
                </tr>
            </thead>

            <tbody>
                <% session[:product_cart].each do |product| %>
                    <tr class="align-middle">
                        <td>
                            <div class="d-flex flex-column">
                                <strong><%= Product.find(product[0].to_i).name %></strong>
                                <label>₹ <%= Product.find(product[0].to_i).price %>&nbsp; x <%= product[1] %></label>
                            </div>
                        </td>
                        <td>₹ <%= Product.find(product[0].to_i).price * product[1] %></td>
                        <td><%= button_to "Remove from cart", cart_remove_product_path(product[0]) %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
<% else %>
    No Products in cart!
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body class="m-5">
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %> ₹
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<table class="table table-hover w-50">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %> |
<%= link_to 'Cart', cart_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<strong>Name:</strong>
<%= @product.name %> </br>
<strong>Price:</strong>
<%= @product.price %>
<hr>

<% if session[:product_cart]["#{@product.id}"] %>
  <p>Added to card</p>
  <div class="d-flex align-items-center my-3">
    <strong>Quantity :</strong>
    <%= button_to "-", products_remove_path(@product), class:"mx-2" %>
    <%= session[:product_cart]["#{@product.id}"] || 0%>
    <%= button_to "+", products_add_path(@product), class:"mx-2" %>
  </div>
<% else %>
  <%= button_to "Add to cart", products_add_path(@product), class:"mx-2 my-2" %>
<% end %>
<hr>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>